# Permalinks
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
relative_permalinks: true

# Setup
title:               Robert Claypool
description:         This is the personal blog and portfolio of Robert Claypool.
baseurl:             ""
tagline:
url:                 http://robert-claypool.github.io
paginate:            5

# Build settings
markdown: kramdown

# Assets
# We specify the directory for Jekyll so we can use @imports.
sass:
  sass_dir:          _sass
  style:            :compressed

# About/contact
author:
  name:              Robert Claypool
  url:               https://twitter.com/robertclaypool
  email:             robert.g.claypool@gmail.com

# Custom vars
version:             0.1.0
github:
  repo:              https://github.com/robert-claypool/robert-claypool.github.io
